- name: Install redis
  zypper:
    name: redis
    state: present

- name: Copy the default redis config
  copy:
    src: /etc/redis/redis.default.conf.template
    dest: /etc/redis/default.conf
    remote_src: yes
    owner: root
    group: redis
    mode: '0640'
    force: no
  notify:
    - Restart redis
