---

- name: Install redis
  zypper:
    name: redis
    state: present

- name: Copy the default redis config
  copy:
    src: /etc/redis/default.conf.example
    dest: /etc/redis/redis.conf
    remote_src: yes
  notify:
  - Restart redis

- name: Copy systemd service file
  copy:
    src: redis.service
    dest: /etc/systemd/system/redis.service
  notify:
  - Restart redis
