- name: Install redis
  zypper:
    name: redis
    state: present

- name: Copy the default redis config
  copy:
    src: default.conf
    dest: /etc/redis/default.conf
    owner: root
    group: redis
    mode: '0640'
  notify:
    - Restart redis
