---

packages:
# utils
- pwgen
- screen
- rsync
- git
- the_silver_searcher
- tree

# editor
- vim
- nano
- emacs-nox

# compression
- zip
- unzip
- bzip2

# monitoring
- dstat
- htop
- iotop
- iftop
- ncdu

# network
- telnet
- wget
- curl
- nmap

# hardware
- smartmontools
- lsscsi
- pv
- lsof
- inxi
