- name: Install nginx and certbot
  zypper:
    name:
    - nginx
    - apache2-utils
    - python3-certbot-nginx
    state: present

- name: Copy 502.html
  copy:
    src: 502.html
    dest: /srv/www/htdocs/502.html
