- name: Install nginx and certbot
  zypper:
    name:
    - nginx
    - apache2-utils
    - python3-certbot-nginx
    state: present
  notify: Restart nginx

- name: Allow nginx to connect to upstream services
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Copy conf.d
  copy:
    src: "conf.d/{{ item }}"
    dest: /etc/nginx/conf.d/{{ item }}
  loop:
  - limit.conf
  - verify.conf

- name: Create snippets directory
  file:
    path: /etc/nginx/snippets/
    state: directory

- name: Copy snippets
  copy:
    src: "snippets/{{ item }}"
    dest: /etc/nginx/snippets/{{ item }}
  loop:
  - content-disposition.conf
  - cors.conf
  - csp.conf
  - limit.conf
  - error.conf
  - ssl.conf

- name: Copy index.html
  template:
    src: index.html
    dest: /srv/www/htdocs/index.html
  notify: Restart nginx

- name: Create internal directory
  file:
    path: /srv/www/internal
    state: directory

- name: Copy htdocs
  copy:
    src: "internal/{{ item }}"
    dest: "/srv/www/internal/{{ item }}"
  loop:
  - 404.html
  - 502.html
  - 503.html
  - 50x.html
  - verify.html
  notify: Restart nginx
