---

- name: all hosts
  hosts: all
  become: yes
  become_user: root
  roles:
  - role: config
    tags: ['config']
  - role: packages
    tags: ['packages']
  - role: nginx
    tags: ['nginx']
  - role: redis
    tags: ['redis']
  - role: isimip-data
    tags: ['isimip-data']
    when: ansible_host == "data.isimip.org"
  - role: isimip-files-api
    tags: ['isimip-files-api']
    when: ansible_host == "files.isimip.org"
  - role: isimip-publisher
    tags: ['isimip-publisher']
    when: ansible_host == "files.isimip.org"
