---

- name: all hosts
  hosts: all
  user: root
  roles:
  - role: config
    tags: ['config']
  - role: ssh
    tags: ['ssh']
  - role: packages
    tags: ['packages']
  - role: nginx
    tags: ['nginx']
  - role: isimip_data
    tags: ['isimip_data']
  - role: isimip_files_api
    tags: ['isimip_data']
