---

- name: all hosts
  hosts: all
  become: yes
  become_user: root
  roles:
  - role: config
    tags: config
  - role: packages
    tags: packages
  - role: nginx
    tags: nginx
  - role: redis
    tags: redis

- name: data.isimip.org
  hosts: data
  become: yes
  become_user: root
  roles:
  - role: isimip-data
    tags: isimip-data

- name: files.isimip.org
  hosts: files
  become: yes
  become_user: root
  roles:
  - role: isimip-files
    tags: isimip-files
  - role: isimip-files-api
    tags: isimip-files-api
  - role: isimip-publisher
    tags: isimip-publisher
