- name: Install dependencies
  zypper:
    name:
    - gcc
    - gcc-c++
    - python3-devel
    - libproj-devel
    - geos-devel
    state: present

- name: Clone repositories
  become: true
  become_user: isimip
  git:
    repo: "https://github.com/ISI-MIP/{{ item }}"
    dest: "/home/isimip/code/isimip/{{ item }}"
    update: no
  loop:
  - isimip-publisher
  - isimip-utils

- name: Create /data
  file:
    path: "{{ item }}"
    state: directory
    owner: isimip
    group: isimip
    mode: '0755'
  with_items:
  - /data
  - /data/public
  - /data/archive
