- name: Add the isimip group
  group:
    name: isimip
    gid: 2000
    state: present

- name: Add the isimip user
  user:
    name: isimip
    comment: isimip user
    uid: 2000
    group: isimip
    shell: /bin/bash

- name: Install PostgreSQL 15
  zypper:
    name:
    - postgresql15
    - postgresql15-server
    - postgresql15-devel
    state: present
- name: Create /srv/www/prod or /srv/www/dev for isimip-data
  file:
    path: /srv/www/{{ env }}
    state: directory
    owner: isimip
    group: isimip

- name: Clone the isimip-data repo
  become: yes
  become_user: isimip
  git:
    repo: 'https://github.com/ISI-MIP/isimip-data'
    dest: /srv/www/{{ env }}
    update: no
  notify:
  - Run manage.py deploy
  - Restart gunicorn

- name: Upgrade the isimip-data repo
  become: yes
  become_user: isimip
  git:
    repo: 'https://github.com/ISI-MIP/isimip-data'
    dest: /srv/www/{{ env }}
    update: yes
    force: yes
  notify:
  - Run manage.py deploy
  - Restart gunicorn
  tags:
  - upgrade
  - never

- name: Copy systemd service files
  template:
    src: "data.service"
    dest: "/etc/systemd/system/{{ env }}.service"
  notify:
  - Restart gunicorn

- name: Create nginx config for data.isimip.org
  template:
    src: "{{ data_url }}.conf"
    dest: /etc/nginx/vhosts.d/{{ data_url }}.conf
  when: "'data' in group_names"
  notify:
  - Restart nginx
