- name: Prepare directories
  file:
    path: /srv/www/{{ item.app }}
    state: directory
    owner: isimip
    group: isimip
  loop: "{{ environments }}"

- name: Create links
  become: true
  become_user: isimip
  file:
    src: /srv/www/{{ item.app }}
    dest: /home/isimip/{{ item.app }}
    state: link
  loop: "{{ environments }}"

- name: Clone the isimip-data repo
  become: true
  become_user: isimip
  git:
    repo: 'https://github.com/ISI-MIP/isimip-data'
    dest: /srv/www/{{ item.app }}
    update: no
  loop: "{{ environments }}"

- name: Copy systemd service files
  template:
    src: systemd.service
    dest: "/etc/systemd/system/{{ item.app }}.service"
  loop: "{{ environments }}"

- name: Copy nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/vhosts.d/{{ item.data_url }}.conf
  loop: "{{ environments }}"
