map $uri $route_key {
    ~^/datasets/ "1";
    ~^/files/    "1";
    ~filelist$   "1";
    ~manifest$   "1";
    default      "";
}

limit_req_zone $binary_remote_addr zone=remote_host:10m rate=4r/s;
limit_req_zone $route_key zone=route:1m rate=10r/s;
