include /etc/redis/includes/redis.defaults.conf

port 6379
dir /var/lib/redis/default/
pidfile /run/redis/default.pid
logfile /var/log/redis/default.log

# cap memory at 256 MB and evict the least-recently-used key, when the limit is hit
maxmemory 256mb
maxmemory-policy allkeys-lru

# Disable append-only file (AOF) persistence and RDB snapshots
appendonly no
save ""
