- name: Copy /root/.bash_aliases
  copy:
    src: bash_aliases
    dest: /root/.bash_aliases

- name: Copy/etc/skel/.bash_aliases
  copy:
    src: bash_aliases
    dest: /etc/skel/.bash_aliases

- name: Include .bash_aliases in /root/.bashrc
  lineinfile:
    dest: /root/.bashrc
    line: "source /root/.bash_aliases"
    create: yes

- name: Include .bash_aliases in /etc/skel/.bashrc
  lineinfile:
    dest: /etc/skel/.bashrc
    line: "source ~/.bash_aliases"
    create: yes

- name: Copy /root/.emacs
  copy:
    src: emacs
    dest: /root/.emacs

- name: Copy /etc/skel/.emacs
  copy:
    src: emacs
    dest: /etc/skel/.emacs
