upstream draft {
    server 127.0.0.1:9002;
    keepalive 16;
}

server {
    server_name {{ draft_url }};

    access_log /var/log/nginx/{{ draft_url }}.access.log;
    error_log /var/log/nginx/{{ draft_url }}.error.log;

    {% if ssl -%}
    listen [::]:443 ssl;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/{{ draft_url }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ draft_url }}/privkey.pem;

    include /etc/nginx/snippets/gzip.conf;
    include /etc/nginx/snippets/ssl.conf;
    {% else -%}
    listen [::]:80;
    listen 80;
    {% endif %}

    root /srv/www/htdocs;
    index index.html;

    client_max_body_size 32M;

    proxy_connect_timeout 10s;
    proxy_send_timeout 15s;
    proxy_read_timeout 30s;

    location /doi/ {
        # uncomment for maintenance
        # return 503;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://draft;  # no trailing slash

        {% if ssl -%}
        include /etc/nginx/snippets/csp.conf;
        {% endif %}
    }
    location /doi/static/ {
        {% if ssl -%}
        include /etc/nginx/snippets/csp.conf;
        {% endif %}
        alias /srv/www/doi/static_root/;
    }

    location /protocol/ {
        alias /srv/www/protocol/;
    }

    include /etc/nginx/snippets/error.conf;
}

{% if ssl %}
server {
    if ($host = {{ draft_url }}) {
        return 301 https://$host$request_uri;
    }

    server_name {{ draft_url }};

    listen 80;
    listen [::]:80;
    return 404;
}
{% endif %}
