- name: Restart gunicorn
  systemd:
    name: "{{ env }}"
    state: restarted
    enabled: yes

- name: Run manage.py deploy
  become: yes
  become_user: isimip
  shell:
    cmd: /bin/bash -c "env/bin/python manage.py deploy"
    chdir: /srv/www/{{ env }}
