server {
    server_name {{ files_url }};

    access_log /var/log/nginx/{{ files_url }}.access.log;
    access_log /var/log/nginx/{{ files_url }}.access.json.log json;
    error_log /var/log/nginx/{{ files_url }}.error.log;

    {% if ssl -%}
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/{{ files_url }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ files_url }}/privkey.pem;

    include /etc/nginx/snippets/csp.conf;
    include /etc/nginx/snippets/ssl.conf;
    {% else -%}
    listen [::]:80;
    listen 80;
    {% endif %}

    root /data/public/;
    index index.html;

    client_max_body_size 128M;

    proxy_read_timeout 120;
    proxy_connect_timeout 120;
    proxy_send_timeout 120;

    if ($needs_verification) {
        return 418;
    }

    location / {
        # uncomment for maintenance
        # return 503;

        try_files $uri $uri/ =404;

        autoindex on;
        autoindex_exact_size off;

        include /etc/nginx/snippets/limit.conf;
        include /etc/nginx/snippets/cors.conf;
        include /etc/nginx/snippets/content-disposition.conf;
    }
    location /restricted/ {
        try_files $uri $uri/ =404;
        alias /data/restricted/;
        autoindex on;

        auth_request /auth;

        include /etc/nginx/snippets/cors.conf;
        include /etc/nginx/snippets/content-disposition.conf;
    }
    location /dev {
        # uncomment for maintenance
        # return 503;

        if ($needs_verification) {
            return 418;
        }

        try_files $uri $uri/ =404;
        alias /data/dev/public/;
        autoindex on;

        include /etc/nginx/snippets/limit.conf;
        include /etc/nginx/snippets/cors.conf;
        include /etc/nginx/snippets/content-disposition.conf;
    }
    location /api/v1 {
        default_type application/json;
        return 410 '{"error":"This API version is deprecated. Please use /api/v2"}';
    }
    location /api/v2/output {
        try_files $uri $uri/ =404;
        alias /data/api/v2/public;
        include /etc/nginx/snippets/cors.conf;
    }
    location /api/v2 {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_pass http://127.0.0.1:9000/;

        client_max_body_size 32M;
        include /etc/nginx/snippets/cors.conf;
    }
    location /qa {
        try_files $uri $uri/ =404;
        alias /data/qa/;
        autoindex on;

        include /etc/nginx/snippets/cors.conf;
    }
    location /cama-flood {
        return 301 https://doi.org/10.48364/ISIMIP.303619;
    }
    location = /auth {
        internal;
        proxy_pass http://127.0.0.1:9002/validate;
        proxy_pass_request_body off;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header Content-Length "";
    }

    include /etc/nginx/snippets/error.conf;
}

{% if ssl %}
server {
    if ($host = {{ files_url }}) {
        return 301 https://$host$request_uri;
    }

    server_name {{ files_url }};

    listen 80;
    listen [::]:80;
    return 404;
}
{% endif %}
