error_page 404 /404.html;
location = /404.html {
    root /srv/www/internal/;
    internal;
    add_header Content-Security-Policy "" always;
}

error_page 502 /502.html;
location = /502.html {
    root /srv/www/internal/;
    internal;
    add_header Content-Security-Policy "" always;
}

error_page 503 /503.html;
location = /503.html {
    root /srv/www/internal/;
    internal;
    add_header Content-Security-Policy "" always;
}

location = /503-disabled.html {
    root /srv/www/internal;
    internal;
}

error_page 500 504 /50x.html;
location = /50x.html {
    root /srv/www/internal/;
    internal;
    add_header Content-Security-Policy "" always;
}

error_page 418 = /verify.html;
location = /verify.html {
    internal;
    root /srv/www/internal/;
    add_header Content-Security-Policy "" always;
}

error_page 429 = /429.html;
location = /429.html {
    internal;
    root /srv/www/internal/;
    add_header Content-Security-Policy "" always;
}
