- name: Install postgres
  zypper:
    name:
    - postgresql18
    - postgresql18-server
    - postgresql18-contrib
    state: present
  notify: Restart postgresql

- name: Check if cluster is initialized
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata

- name: Initialize the cluster
  become: true
  become_user: postgres
  command: /usr/lib/postgresql18/bin/initdb -D /var/lib/pgsql/data
  when: not pgdata.stat.exists
