alias ls='ls --color=auto'
alias ll='ls -lah'

alias e='emacs'
alias h='history'
alias p='python'
alias t='tail -f'
alias grep='grep --color'

alias gits='git status'
alias gitc='git commit -am'
alias gitl='git log --oneline'
alias gitb='git branch'

alias sd='sudo -i'
alias ap='aptitude'

alias ve='source env/bin/activate'
alias de='deactivate'

alias psg='ps auxw | grep --color'
alias eng='env | grep --color'
