alias ls='ls --color=auto'
alias ll='ls -lah'

alias e='emacs'
alias h='history'
alias p='python'
alias t='tail -f'
alias grep='grep --color'

alias gits='git status'
alias gitc='git commit -am'
alias gitl='git log'
alias gitb='git branch'

alias sd='sudo -i'
alias sp='sudo -i -u postgres'
alias ap='aptitude'
alias psg='ps auxw | grep --color'

alias ve='source env/bin/activate'
alias de='deactivate'

alias ag='ripgrep'
alias dstat='dool'

function mkenv {
    python3 -m venv env;
    source env/bin/activate;
    pip install --upgrade pip setuptools wheel;
}
